In [1]:
import pandas as pd
import seaborn as sns
import matplotlib 
%matplotlib inline
pd.set_option('display.max_columns',None)
pd.options.display.max_seq_items = 2000
# pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import requests, re
import nltk
import string, itertools
from collections import Counter, defaultdict
# from nltk.text import Text
# from nltk.probability import FreqDist
# from nltk.tokenize import word_tokenize, sent_tokenize, regexp_tokenize
# from nltk.corpus import stopwords
# from nltk.stem import PorterStemmer, WordNetLemmatizer
# from gensim.corpora.dictionary import Dictionary
# from gensim.models.tfidfmodel import TfidfModel
from sklearn.cluster import KMeans

In [2]:
import json
import pandas as pd
data_file_1 = open("../data/yelp_academic_dataset_business.json")
data_1 = []
for line in data_file_1:
    data_1.append(json.loads(line))
business = pd.DataFrame(data_1)
data_file_1.close()

In [3]:
## drop unuseful column 'hours','attributes'
business.drop(['hours','attributes'], axis=1, inplace=True)

## remove quotation marks in name and address column
business.name=business.name.str.replace('"','')
business.address=business.address.str.replace('"','')#把引号去掉

## 按洲名简写筛选数据，
## 并存入新的dataframe：use
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
usa=business.loc[business['state'].isin(states)] #把不是美国州的去掉
business.head()

              business_id                      name                          address           city state postal_code   latitude   longitude  stars  review_count  is_open                                         categories
0  Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ           1616 Chapala St, Ste 2  Santa Barbara    CA       93101  34.426679 -119.711197    5.0             7        0  Doctors, Traditional Chinese Medicine, Naturop...
1  mpf3x-BjTdTEA3yCZrAYPw             The UPS Store  87 Grasso Plaza Shopping Center         Affton    MO       63123  38.551126  -90.335695    3.0            15        1  Shipping Centers, Local Services, Notaries, Ma...
2  tUFrWirKiKi_TAnsVWINQQ                    Target             5255 E Broadway Blvd         Tucson    AZ       85711  32.223236 -110.880452    3.5            22        0  Department Stores, Shopping, Fashion, Home & G...
3  MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries                      935 Race St   Philadelphia    PA       19107  39.955505  -75.155564    4.0            80        1  Restaurants, Food, Bubble Tea, Coffee & Tea, B...
4  mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery                    101 Walnut St     Green Lane    PA       18054  40.338183  -75.471659    4.5            13        1                          Brewpubs, Breweries, Food

In [4]:
usa=usa.dropna(axis=0, subset=['categories'])

In [5]:
## 选出所有餐厅，
## 并存入新的dataframe：us_restaurants
us_restaurants=usa[usa['categories'].str.contains('Restaurants')]

## select out 16 cuisine types of restaurants and rename the category
## 把 us_restaurants['category'] 中含有指定种类的餐厅筛选出来，
## 并新建column：'category'

# us_restaurants.is_copy=False 版本过老
us_restaurants['category']=pd.Series()
us_restaurants.loc[us_restaurants.categories.str.contains('American'),'category'] = 'American'
us_restaurants.loc[us_restaurants.categories.str.contains('Mexican'), 'category'] = 'Mexican'
us_restaurants.loc[us_restaurants.categories.str.contains('Italian'), 'category'] = 'Italian'
us_restaurants.loc[us_restaurants.categories.str.contains('Japanese'), 'category'] = 'Japanese'
us_restaurants.loc[us_restaurants.categories.str.contains('Chinese'), 'category'] = 'Chinese'
us_restaurants.loc[us_restaurants.categories.str.contains('Thai'), 'category'] = 'Thai'
us_restaurants.loc[us_restaurants.categories.str.contains('Mediterranean'), 'category'] = 'Mediterranean'
us_restaurants.loc[us_restaurants.categories.str.contains('French'), 'category'] = 'French'
us_restaurants.loc[us_restaurants.categories.str.contains('Vietnamese'), 'category'] = 'Vietnamese'
us_restaurants.loc[us_restaurants.categories.str.contains('Greek'),'category'] = 'Greek'
us_restaurants.loc[us_restaurants.categories.str.contains('Indian'),'category'] = 'Indian'
us_restaurants.loc[us_restaurants.categories.str.contains('Korean'),'category'] = 'Korean'
us_restaurants.loc[us_restaurants.categories.str.contains('Hawaiian'),'category'] = 'Hawaiian'
us_restaurants.loc[us_restaurants.categories.str.contains('African'),'category'] = 'African'
us_restaurants.loc[us_restaurants.categories.str.contains('Spanish'),'category'] = 'Spanish'
us_restaurants.loc[us_restaurants.categories.str.contains('Middle_eastern'),'category'] = 'Middle_eastern'
us_restaurants[:20]

/var/folders/2s/l91lc7n15_v8ttwq_5b399f40000gn/T/ipykernel_84151/3096763070.py:10: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  us_restaurants['category']=pd.Series()
/var/folders/2s/l91lc7n15_v8ttwq_5b399f40000gn/T/ipykernel_84151/3096763070.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_restaurants['category']=pd.Series()

               business_id                                 name               address          city state postal_code   latitude   longitude  stars  review_count  is_open                                         categories    category
3   MTSW4McQd7CbVtyjqoe9mw                   St Honore Pastries           935 Race St  Philadelphia    PA       19107  39.955505  -75.155564    4.0            80        1  Restaurants, Food, Bubble Tea, Coffee & Tea, B...         NaN
5   CF33F8-E6oudUQ46HnavjQ                       Sonic Drive-In         615 S Main St  Ashland City    TN       37015  36.269593  -87.058943    2.0             6        1  Burgers, Fast Food, Sandwiches, Food, Ice Crea...         NaN
8   k0hlBqXX-Bt0vf1op7Jr1w                Tsevi's Pub And Grill     8025 Mackenzie Rd        Affton    MO       63123  38.565165  -90.321087    3.0            19        0  Pubs, Restaurants, Italian, Bars, American (Tr...       Greek
9   bBDDEgkFA1Otx9Lfe7BZUQ                       Sonic Drive-In   2312 Dickerson Pike     Nashville    TN       37207  36.208102  -86.768170    1.5            10        1  Ice Cream & Frozen Yogurt, Fast Food, Burgers,...         NaN
11  eEOYSgkmpB90uNA7lDOMRA                Vietnamese Food Truck                           Tampa Bay    FL       33602  27.955269  -82.456320    4.0            10        1         Vietnamese, Food, Restaurants, Food Trucks  Vietnamese
12  il_Ro8jwPlHresjw9EGmBg                              Denny's          8901 US 31 S  Indianapolis    IN       46227  39.637133  -86.127217    2.5            28        1  American (Traditional), Restaurants, Diners, B...    American
14  0bPLkL0QhhPO5kt1_EXmNQ                 Zio's Italian Market         2575 E Bay Dr         Largo    FL       33771  27.916116  -82.760461    4.5           100        0        Food, Delis, Italian, Bakeries, Restaurants     Italian
15  MUTTqe8uqyMdBl186RmNeA                             Tuna Bar           205 Race St  Philadelphia    PA       19106  39.953949  -75.143226    4.0           245        1                  Sushi Bars, Restaurants, Japanese    Japanese
19  ROeacJQwBeh05Rqg7F6TCg                                  BAP         1224 South St  Philadelphia    PA       19147  39.943223  -75.162568    4.5           205        1                                Korean, Restaurants      Korean
22  kfNv-JZpuN6TVNSO6hHdkw                      Hibachi Express        6625 E 82nd St  Indianapolis    IN       46250  39.904320  -86.053080    4.0            20        1             Steakhouses, Asian Fusion, Restaurants         NaN
23  9OG5YkX1g2GReZM0AskizA              Romano's Macaroni Grill    5505 S Virginia St          Reno    NV       89502  39.476117 -119.789339    2.5           339        1                               Restaurants, Italian     Italian
24  4iRzR7OaS-QaSXuvYxEGKA                            Super Dog  1160 Gallatin Pike S     Nashville    TN       37115  36.248570  -86.719986    4.0             6        0                              Hot Dogs, Restaurants         NaN
27  tMkwHmWFUEXrC9ZduonpTg                   The Green Pheasant         215 1st Ave S     Nashville    TN       37201  36.159886  -86.773197    4.0           161        0                     Restaurants, Japanese, Seafood    Japanese
28  QdN72BWoyFypdGJhhI5r7g                              Bar One          767 S 9th St  Philadelphia    PA       19147  39.939825  -75.157447    4.0            65        0  Cocktail Bars, Bars, Italian, Nightlife, Resta...     Italian
29  sqSqqLy0sN8n2IZrAbzidQ                       Domino's Pizza     3001 Highway 31 W   White House    TN       37188  36.464747  -86.659187    3.5             8        1      Pizza, Chicken Wings, Sandwiches, Restaurants         NaN
31  Mjboz24M9NlBeiOJKLEd_Q                     DeSandro on Main          4105 Main St  Philadelphia    PA       19127  40.022466  -75.218314    3.0            41        0                    Pizza, Restaurants, Salad, Soup         NaN
33  kV_Q1oqis8Qli8dUoGpTyQ                        Ardmore Pizza     10 Rittenhouse Pl       Ardmore    PA       19003  40.006707  -75.289671    3.5           109        1                                 Pizza, Restaurants         NaN
35  aPNXGTDkf-4bjhyMBQxqpQ                           Craft Hall    901 N Delaware Ave  Philadelphia    PA       19123  39.962582  -75.135657    3.5            65        1  Eatertainment, Arts & Entertainment, Brewpubs,...    American
36  2xVsWBNFwZOxIOdd9Mwnww             Cheeseburger In Paradise  116 N Pottstown Pike         Exton    PA       19341  40.029962  -75.630607    2.5            20        0                               Restaurants, Burgers         NaN
41  ljxNT9p0y7YMPx0fcNBGig  Tony's Restaurant & 3rd Street Cafe          312 Piasa St         Alton    IL       62002  38.896563  -90.186203    3.0            94        1  Restaurants, Specialty Food, Steakhouses, Food...     Italian

In [6]:
## drop null values in category, 
us_restaurants=us_restaurants.dropna(axis=0, subset=['category'])

## delete original column categories 
del us_restaurants['categories']

## and reset the index
us_restaurants=us_restaurants.reset_index(drop=True)
us_restaurants.head(10)

              business_id                     name             address          city state postal_code   latitude   longitude  stars  review_count  is_open    category
0  k0hlBqXX-Bt0vf1op7Jr1w    Tsevi's Pub And Grill   8025 Mackenzie Rd        Affton    MO       63123  38.565165  -90.321087    3.0            19        0       Greek
1  eEOYSgkmpB90uNA7lDOMRA    Vietnamese Food Truck                         Tampa Bay    FL       33602  27.955269  -82.456320    4.0            10        1  Vietnamese
2  il_Ro8jwPlHresjw9EGmBg                  Denny's        8901 US 31 S  Indianapolis    IN       46227  39.637133  -86.127217    2.5            28        1    American
3  0bPLkL0QhhPO5kt1_EXmNQ     Zio's Italian Market       2575 E Bay Dr         Largo    FL       33771  27.916116  -82.760461    4.5           100        0     Italian
4  MUTTqe8uqyMdBl186RmNeA                 Tuna Bar         205 Race St  Philadelphia    PA       19106  39.953949  -75.143226    4.0           245        1    Japanese
5  ROeacJQwBeh05Rqg7F6TCg                      BAP       1224 South St  Philadelphia    PA       19147  39.943223  -75.162568    4.5           205        1      Korean
6  9OG5YkX1g2GReZM0AskizA  Romano's Macaroni Grill  5505 S Virginia St          Reno    NV       89502  39.476117 -119.789339    2.5           339        1     Italian
7  tMkwHmWFUEXrC9ZduonpTg       The Green Pheasant       215 1st Ave S     Nashville    TN       37201  36.159886  -86.773197    4.0           161        0    Japanese
8  QdN72BWoyFypdGJhhI5r7g                  Bar One        767 S 9th St  Philadelphia    PA       19147  39.939825  -75.157447    4.0            65        0     Italian
9  aPNXGTDkf-4bjhyMBQxqpQ               Craft Hall  901 N Delaware Ave  Philadelphia    PA       19123  39.962582  -75.135657    3.5            65        1    American

In [7]:
## load review table

# review.head()
import json
import pandas as pd
review = pd.read_csv('yelp_reviews_3.csv')

In [8]:
## 以 'business_id' 为准合并两个df，得到 “restaurants_reviews”
restaurants_reviews = pd.merge(us_restaurants, review, on = 'business_id')
restaurants_reviews.head()

              business_id                                    name                     address          city state postal_code   latitude   longitude  stars  review_count  is_open  category                                               text    labels
0  Dtuf4vD0znzwJW9vk3iTNw  Tomo Japanese Steakhouse and Sushi Bar  7411 N Keystone Ave, Ste A  Indianapolis    IN       46240  39.888725  -86.121213    4.0           246        1  Japanese  i can only speak for the lunch special which i...  positive
1  dJfkfBbJz7wi0RgW-ph_Eg                              Sake House           5106 E Fowler Ave         Tampa    FL       33617  28.055212  -82.399374    3.0           140        0  Japanese  we've been visiting sake house fairly regularl...  negative
2  dJfkfBbJz7wi0RgW-ph_Eg                              Sake House           5106 E Fowler Ave         Tampa    FL       33617  28.055212  -82.399374    3.0           140        0  Japanese  i went to have dinner with my friend and 2 you...  negative
3  f82dhKNiUXsDVPMLqKYiIQ                           Sher-e-Punjab           853 East Grant Rd        Tucson    AZ       85719  32.250960 -110.959158    4.0           446        1    Indian  having enjoyed lunches and dinners at sherepun...  negative
4  VeqkfRUzZAKlQer3npXPdQ                     New India's Kitchen         14222 Manchester Rd       Ballwin    MO       63011  38.592057  -90.503565    4.0           130        0    Indian  this is the best indian lunch buffet in stl th...  positive

In [9]:
## 更新 column names
#restaurants_reviews.rename(columns={'stars_x':'avg_star','stars_y':'review_star'}, inplace=True)

## 把评论中所有的：特殊符号和换行符 全部用空格替换，然后计算每个评论的字数并存入 'num_words_review'
#restaurants_reviews['text'] = restaurants_reviews.text.str.replace('\n','').str.replace('[!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~]','').map(lambda x: len(x.split()))

# 根据星级，对评论 label reviews as positive or negative
#restaurants_reviews['labels'] = ''
#restaurants_reviews.loc[restaurants_reviews.review_star >=4, 'labels'] = 'positive'
#restaurants_reviews.loc[restaurants_reviews.review_star ==3, 'labels'] = 'neural'
#restaurants_reviews.loc[restaurants_reviews.review_star <3, 'labels'] = 'negative'

# drop neutral reviews for easy analysis
#restaurants_reviews.drop(restaurants_reviews[restaurants_reviews['labels'] =='neural'].index, axis=0, inplace=True)
restaurants_reviews.reset_index(drop=True, inplace=True)

In [10]:
restaurants_reviews.head()

              business_id                                    name                     address          city state postal_code   latitude   longitude  stars  review_count  is_open  category                                               text    labels
0  Dtuf4vD0znzwJW9vk3iTNw  Tomo Japanese Steakhouse and Sushi Bar  7411 N Keystone Ave, Ste A  Indianapolis    IN       46240  39.888725  -86.121213    4.0           246        1  Japanese  i can only speak for the lunch special which i...  positive
1  dJfkfBbJz7wi0RgW-ph_Eg                              Sake House           5106 E Fowler Ave         Tampa    FL       33617  28.055212  -82.399374    3.0           140        0  Japanese  we've been visiting sake house fairly regularl...  negative
2  dJfkfBbJz7wi0RgW-ph_Eg                              Sake House           5106 E Fowler Ave         Tampa    FL       33617  28.055212  -82.399374    3.0           140        0  Japanese  i went to have dinner with my friend and 2 you...  negative
3  f82dhKNiUXsDVPMLqKYiIQ                           Sher-e-Punjab           853 East Grant Rd        Tucson    AZ       85719  32.250960 -110.959158    4.0           446        1    Indian  having enjoyed lunches and dinners at sherepun...  negative
4  VeqkfRUzZAKlQer3npXPdQ                     New India's Kitchen         14222 Manchester Rd       Ballwin    MO       63011  38.592057  -90.503565    4.0           130        0    Indian  this is the best indian lunch buffet in stl th...  positive

In [12]:
import csv
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
pd.set_option('display.float_format', lambda x: '%.4f' % x)


## convert text to lower case 全部转化为小写
#restaurants_reviews.text = restaurants_reviews.text.str.lower()

## remove unnecessary punctuation（又重复操作了一遍）
#restaurants_reviews['removed_punct_text']= restaurants_reviews.text.str.replace('\n','').str.replace('[!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~]','')

# ## 将 positive file 导入 list：positive_words中
# file_positive = open('/Users/houdeliao/Desktop/positive.txt')
# reader =csv.reader(file_positive)
# positive_words = [word[0] for word in reader]


import sys
positive_words=[]
with open('../data/positive.txt','r') as p:
    for pline in p:
        positive_words.append(pline.strip('\n'))



## 将 negative file 导入 list：negative_words中
file_negative = open('../data/negative2.txt')
reader =csv.reader(file_negative)
negative_words = [word[0] for word in reader]


# negative_words=[]
# with open('/Users/houdeliao/Desktop/negative.txt','r') as n:
#     for nline in n:
#         negative_words.append(nline.strip('\n'))
# print(negative_words)

In [13]:
"""
创立函数
"""
## get dataset by category
def get_dataset(category):
    df = restaurants_reviews[['text','labels']][restaurants_reviews.category==category]
    df.reset_index(drop=True, inplace =True)
    #df.rename(columns={'removed_punct_text':'text'}, inplace=True)
    return df

In [14]:
## only keep positive and negative words
def filter_words(review):
    words = [word for word in review.split() if word in positive_words + negative_words]
    words = ' '.join(words)
    return words

In [27]:
## 得到重要性评分
def get_polarity_score(dataset):
    dataset.text = dataset.text.apply(filter_words)
    
    terms_train=list(dataset['text'])
    class_train=list(dataset['labels'])
    
    ## get bag of words
    vectorizer = CountVectorizer()
    feature_train_counts=vectorizer.fit_transform(terms_train)
    
    ## run model
    svm = LinearSVC()
    svm.fit(feature_train_counts, class_train)
    print(class_train)
    
    ## create dataframe for score of each word in a review calculated by svm model
    coeff = svm.coef_[0]
    cuisine_words_score = pd.DataFrame({'score': coeff, 'word': vectorizer.get_feature_names()})
    print(cuisine_words_score)
    
    ## get frequency of each word in all reviews in specific category
    cuisine_reviews = pd.DataFrame(feature_train_counts.toarray(), columns=vectorizer.get_feature_names())
    cuisine_reviews['labels'] = class_train
    cuisine_frequency = cuisine_reviews[cuisine_reviews['labels'] =='positive'].sum()[:-1]
    
    cuisine_words_score.set_index('word', inplace=True)
    cuisine_polarity_score = cuisine_words_score
    cuisine_polarity_score['frequency'] = cuisine_frequency
    
    cuisine_polarity_score.score = cuisine_polarity_score.score.astype(float)
    cuisine_polarity_score.frequency = cuisine_polarity_score.frequency.astype(int)
    
    ## calculate polarity score 
    cuisine_polarity_score['polarity'] = cuisine_polarity_score.score * cuisine_polarity_score.frequency / cuisine_reviews.shape[0]
    
    cuisine_polarity_score.polarity = cuisine_polarity_score.polarity.astype(float)
    ## drop unnecessary words
    unuseful_positive_words = ['great','amazing','love','best','awesome','excellent','good',
                                                   'favorite','loved','perfect','gem','perfectly','wonderful',
                                                    'happy','enjoyed','nice','well','super','like','better','decent','fine',
                                                    'pretty','enough','excited','impressed','ready','fantastic','glad','right',
                                                    'fabulous','liked','incredible','outstanding','positive']
    unuseful_negative_words =  ['bad','disappointed','disappointing','horrible','disappoint','lacking','unfortunately','sorry']
    unuseful_words = unuseful_positive_words + unuseful_negative_words
    print(cuisine_polarity_score)
    for word in cuisine_polarity_score.index:
        if word in unuseful_words:
            cuisine_polarity_score.drop(word, axis=0, inplace=True)
            
    #cuisine_polarity_score.drop(cuisine_polarity_score.loc[unuseful_words].index, axis=0, inplace=True)
    
    return cuisine_polarity_score,vectorizer,svm

In [16]:
def get_top_words(dataset, label, number=20):
    if label == 'positive':
        df = dataset[dataset.polarity>0].sort_values('polarity',ascending = False)[:number]
    else:
        df = dataset[dataset.polarity<0].sort_values('polarity')[:number]
    return df

In [17]:
def split_data(dataset, test_size):
    df_train, df_test = train_test_split(dataset[['text','labels']],test_size=test_size)
    return df_train,df_test

In [40]:
from sklearn.metrics import accuracy_score
def test_data(dataset,transform,model):
    x_test=list(dataset['text'])
    y_test=list(dataset['labels'])
    
    ## get bag of words
    print(x_test[1])
    feature_train_counts=transform.transform(x_test)
    y_predict=model.predict(feature_train_counts)
    print(y_predict)
    
    
    score=accuracy_score(y_predict,y_test)
    
    return score
Japanese_test_score=test_data(Japanese_test,vectorizer_Jap,svm_Jap)

this is one of my go to lunch places in my neighborhood the maki specials for lunch are spot on and you get so much sushi for the money i like the crunchy bagel roll but i'm a plain sushi kind of girl pretty okay service decent food great prices right down the street you can find me there most weeks
['negative' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'negative' 'positive' 'negative'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'positive' 'negative' 'negative' 'negative' 'positive' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'negative' 'positive'
 'positive' 'negative' 'positive' 'negative' 'negative' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'negative' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'negative' 'negative' 'negative' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'negative' 'positive' 'negative' 'positive' 'positive' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive']

In [34]:
Japanese_reviews = get_dataset('Japanese')
Japanese_train,Japanese_test = split_data(Japanese_reviews, 0.9)
print('Total %d number of reviews' % Japanese_train.shape[0])
print(Japanese_reviews)

Total 20 number of reviews
                                                  text    labels
0    i can only speak for the lunch special which i...  positive
1    we've been visiting sake house fairly regularl...  negative
2    i went to have dinner with my friend and 2 you...  negative
3    disappointed our lunch order took nearly an ho...  negative
4    the prices listed online through google were l...  negative
5    my food was extremely salty to a point where i...  negative
6    i was so impressed with ichicoro when i first ...  negative
7    this is the best sushi location in the area i ...  positive
8    can't say enough about how fresh and tasty thi...  positive
9    disclaimer this was for carryouti can only bla...  negative
10   finally the sushirrito has come to philadelphi...  positive
11   this is supposed to be the shrimp roll with ma...  negative
12   my husband and i found out this place from a f...  positive
13   i enjoyed every piece of the sushi and think i...  positive
14   the sushi was delicious  fresh fish and ingred...  positive
15   most of the food here is pretty stellar the fu...  positive
16   ordered a party tray for pickup  2 out of 3 vi...  negative
17   my go to sushi place for the area fresh eats d...  positive
18   does not have ramen only half the menu on here...  negative
19   this is my second time ordering from here the ...  negative
20   unfortunately this benihana location has signi...  negative
21   we went here to celebrate the kids getting gre...  positive
22   i had a great experience for my birthday tonig...  positive
23   best unique sushi i've eaten in the st louis a...  positive
24   came here because i had time to kill i love su...  negative
25   omg incredible ramen the broth was so flavorfu...  positive
26   this place sucks it was my birthday and my wif...  negative
27   it pains me to do so but i have to give a less...  negative
28   love this place  staff are always super friend...  positive
29   this place is great super delicious rolls and ...  positive
30   we were blown away by the quality of the sushi...  positive
31   heeyahthat is my kung fu chopping noise while ...  positive
32   happy teriyaki on riverside in eagle just migh...  positive
33   i was with a party of 7 we got seated in a sma...  negative
34   this place is great i had great sushi here goo...  positive
35   if i could give less than 1 star i would we ha...  negative
36   i was craving fujiyama tonight but my daughter...  negative
37   walked in told to seat ourselves on the patio ...  negative
38   i met some coworkers at jackson's after a 5k c...  negative
39   well one star is for location onlybut food exc...  negative
40   great for good takeout japanese foodthe rice m...  positive
41   ikkyu was not my favorite japanese restaurant ...  negative
42   expected a lot more since this place had so ma...  negative
43   kokopelli's has a lot of things going for it u...  negative
44   best sushi aroundexcellent food excellent serv...  positive
45   i'm always pleased with kung fu tea my favorit...  positive
46   this was our first time ordering food in over ...  positive
47   i have an allergy to gluten and was told by th...  negative
48   i recently ate at ajia before a concert i atte...  positive
49   out of nowhere they changed the credit card mi...  negative
50   very great sushi for a cheap price got 7 rolls...  positive
51   we live close to osaki but had never tried it ...  negative
52   dined in for sushi dinner most of their busine...  positive
53   love it here food is always fresh and out fast...  positive
54   poor service waitress very rude the waitress f...  negative
55   this is one of my go to lunch places in my nei...  positive
56   we waited an hour for our sushi we got there a...  negative
57   i really really love this sushi restaurant it ...  positive
58   my wife and i went to origami sushi last night...  negative
59   i'll start by saying that this is my first neg...  negative
60   i love the food here came to this restaurant o...  positive
61   i eat sushi about once every other week this i...  positive
62   stopped in for a late lunch the simplest salad...  positive
63   this restaurant had delicious food and the ser...  positive
64   i'm giving this a one star because i'm super s...  negative
65   this place used to be so good but now they hav...  negative
66   it's pricey for the quality of food the sashim...  negative
67   absolute rubbishtired old fishwasabi that glow...  negative
68   i would rate this place a one but the saving g...  negative
69   simply my favorite restaurant in boise flavorf...  positive
70   our new favorite sushi place in reno we have a...  positive
71   great food and great atmosphere not a big fan ...  positive
72   i usually got to ijji in sparks when i want su...  positive
73   please do not go here the sushi is terrible li...  negative
74   so we have been here a few times and never had...  negative
75   without a doubt the worst all you could eat ex...  negative
76   their kamamoto oysters were delicious as well ...  positive
77   i don't know about the reviews here but based ...  negative
78   this is the first and last time i will get sus...  negative
79   we've enjoyed all the food we got from teriyak...  negative
80   great place to get good sushi rolls and sashim...  positive
81   didn't even make it to our meal was going to g...  negative
82   for our first official outing as tampa residen...  positive
83   i enjoyed the food but it wasn't mind blowing ...  negative
84   do sushi chef's know the size of a human mouth...  negative
85   hello hidden gem i recently moved to hampton t...  positive
86   this is one of the few restaurants in this are...  negative
87   i was able to dine in and upped my rating by 1...  positive
88   an awesome restaurant the all you can eat sush...  positive
89   service was bad i didn't feel like it was the ...  negative
90   so i've been to this place a few times in the ...  negative
91   excellent sushi superb value this is not an al...  positive
92   always go here love the service love the food ...  negative
93   this place has to be the absolute worst japane...  negative
94   first time and last time going the cashier was...  negative
95   i unfortunately don't live in an area with a l...  positive
96   tried this place today for the first time love...  positive
97   no complaints with the food but the front wait...  negative
98   incredible  took my son here and we both loved...  positive
99   the food my husband had was good  i never got ...  negative
100  this place used to be the  place to be great m...  negative
101  this place is decent for the area and the atmo...  positive
102  my family and i have eaten here twice and love...  negative
103  absolutely deliciousme  my husband got the spi...  positive
104  love this place hands down my favorite sushi i...  positive
105  how do i say this oh thats right overrated the...  negative
106  we came here because we were craving some chic...  negative
107  craving fish in channelside we decided to give...  negative
108  i had a lovely late lunch here on christmas ev...  positive
109  spent 116 for to go order and they still want ...  negative
110  i went here on a friday afternoon after lunch ...  positive
111  working in a restaurant myself i understand th...  negative
112  went here with a group of friends the other ni...  negative
113  we made a reservation at 615 arrived 5 minutes...  negative
114  nama on a thursday night for half off sushi do...  positive
115  i had low expectations for ramen in nashville ...  negative
116  went here on a saturday night and had food poi...  negative
117  when it comes to sushi in the city there are t...  positive
118  ninja was always a go to sushi place for me un...  negative
119  love happy hour runs monfri 47 fresh sushi gre...  positive
120  the menu says the far east wings come with a l...  negative
121  meh a truly uninspiring japanese restaurant th...  negative
122  this place is awesome  great japanese food a w...  positive
123  sushi is garbage prices keep getting higher an...  negative
124  hidden gem in the tampa bay area fresh sushi a...  positive
125  the waiters was good they asked questions and ...  negative
126  i'm sorry to say but had very bad experience l...  negative
127  i just want to make this review to hopefully e...  negative
128  went there for all you can eat bbq and had a s...  negative
129  great atmosphere a perfect place for a date my...  negative
130  best sushi in indy hands down salmon is delici...  positive
131  servers were rude sat in the shitty back room ...  negative
132  wow how does a place go from a 5 star rating t...  negative
133  goleta sushi house is unassuming but it's defi...  positive
134  this place has the best sushi in town whether ...  positive
135  5 damn stars this place is a hidden gem hands ...  positive
136  the best sushi in sj hands down and very frien...  positive
137  got around to going again this past week with ...  positive
138  i just got carry out this evening from sushi a...  negative
139  came to philadelphia for work and decided to c...  positive
140  slightly overrated on yelp good food and good ...  positive
141  ramen  best in town    bbq  is amazing the pri...  positive
142  santa barbara needs more restaurants like the ...  positive
143  great family style dinner  we ordered several ...  positive
144  food was delicious best ramen i've had service...  positive
145  ramen is good but the takoyaki and curry tonka...  positive
146  amazing sushi rolls horrible servicei had to a...  negative
147  loved this place awesome service and fresh fre...  positive
148  i arrived at sushi alive close to closing time...  positive
149  i was invited to this wonderful place this wee...  positive
150  don't be confused with the chicken symbol on t...  positive
151  horrible service we left before we even had a ...  negative
152  not impressed the location and size of this re...  negative
153  two ten jack a japaneseinspired gastropub izak...  positive
154  best sushi i've had the staff was amazing and ...  positive
155  we came here for lunch on saturday and found i...  positive
156  the sushi is so plain i don't like it there un...  negative
157  wow i cannot believe how expensive this i just...  negative
158  closed at 9pm and waited until 859pm to call a...  negative
159  they charge a 10 minimum for credit transactio...  negative
160  far and away my favorite chinesejapanese resta...  positive
161  i am going to give two stars instead of one to...  negative
162  we've been to ichiban twice not for their tepp...  positive
163  we had the early bird special not a bad deal a...  positive
164  super disappointed in the food sushi and servi...  negative
165  ordered black garlic ramen and gyoza from here...  negative
166  i have been patronizing the restaurant for abo...  negative
167  solid kimchi ramen  excellent kimchi better ki...  positive
168  this is my fav location of shogun  they havr h...  positive
169  the first sushi roll was nearly rotten such a ...  negative
170  very rude just came to pick up my sushi and th...  negative
171  when i want my quick fix for sushisalmon this ...  positive
172  we came to this restaurant on a recommendation...  negative
173  honestly just drive 30 minutes and go to ichic...  negative
174  not impressed if you are into sashimi or fish ...  negative
175  i've driven past this place probably 5000 time...  positive
176  we have only gotten take out  sushi isdecent o...  positive
177  why 5 stars because we've been here several ti...  positive
178  no better place to go in tampa for sushi serio...  positive
179  i was visiting tampa for a few days and my fri...  positive
180  umm they forgot to give us a menu enough said ...  negative
181  i had to bump my review to 4 stars  we've eate...  positive
182  super meal  favorite app of all five was the t...  positive
183  haven't tried the ramen yet although i'm excit...  positive
184  this sushi was one of the best in tampa that i...  positive
185  love this location nice to have a space to eat...  positive
186  good sushi horrible service we had a reservati...  negative
187  been here twice both times did not impress sus...  negative
188  we had a very pleasant dinning experience  the...  positive
189  this place sucks very unprofessional one time ...  negative
190  this is definitely the best spot for sushi in ...  positive
191  we ordered take out before and thought this pl...  negative
192  easy to miss because of its location but so gl...  positive
193  so after trying to give this place a second ch...  negative
194  the food was delicious and pretty affordable i...  positive
195  will never be back the most disrespectful plac...  negative
196  i've recently developed a liking for ramen and...  positive
197  service was horrible and the sushi was bleh  t...  negative
198  this was a fabulous discovery i was kind of sk...  positive
199  my so and i absolutely loved the tonkotsu shir...  positive

In [35]:
Japanese_polarity_score,vectorizer_Jap,svm_Jap = get_polarity_score(Japanese_train)
get_top_words(Japanese_polarity_score, 'positive',20)

['negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'positive']
     score           word
0   0.0562        amazing
1  -0.1716      available
2   0.0589        awesome
3  -0.1952            bad
4   0.2413           best
5  -0.1574         better
6   0.0000           bomb
7   0.1124      celebrate
8   0.0000         classy
9  -0.0339          clear
10 -0.3143           cold
11  0.0039  complimentary
12 -0.0339   consistently
13  0.0000           cool
14  0.0207      criticism
15  0.3178         decent
16  0.4828      delicious
17 -0.2561      desirable
18  0.0562   disappointed
19 -0.2804  disappointing
20  0.0000   disintegrate
21 -0.1377  disrespectful
22  0.0000    distraction
23 -0.1274       downhill
24  0.0207        enjoyed
25 -0.0339         enough
26 -0.0339   exaggeration
27  0.0000       fabulous
28  0.0039           fast
29  0.0628       favorite
30  0.0000           fool
31  0.4150          fresh
32  0.0000       friendly
33  0.0000          fuzzy
34  0.0589            gem
35  0.2455           good
36  0.2703          great
37  0.0039           hard
38  0.0039           hate
39  0.0039        honesty
40 -0.2902       horrible
41  0.1798            hot
42 -0.3050      impressed
43  0.1048     incredibly
44  0.1048            led
45  0.0207          lemon
46 -0.0897           like
47  0.0207          liked
48 -0.1525           loud
49  0.1472           love
50 -0.2802           luck
51 -0.0339      miserable
52 -0.0339        mistake
53  0.0223       negative
54  0.0453           nice
55  0.0039         nicely
56  0.0000      oblivious
57 -0.1274          pains
58  0.1579        patient
59  0.1048        perfect
60 -0.1377      perfectly
61  0.0000        popular
62 -0.0339       positive
63 -0.2802        pretend
64  0.1618         pretty
65  0.0000         pricey
66  0.1579          ready
67 -0.0339     reasonably
68  0.0562      recommend
69  0.1736    recommended
70  0.0000           rich
71  0.0000          right
72 -0.1377           rude
73 -0.2561            sad
74  0.0000           safe
75  0.1048      satisfied
76  0.0000      skeptical
77 -0.2804           slow
78 -0.1377        smiling
79  0.0000           soft
80 -0.0339          sorry
81 -0.0000          super
82  0.1048         tender
83  0.1048          tired
84 -0.2561   tremendously
85  0.1048        trusted
86 -0.1274         unable
87 -0.1514  unfortunately
88  0.0000         unreal
89 -0.2802        upscale
90 -0.1318           warm
91 -0.2802          waste
92  0.0039          weird
93  0.0323           well
94  0.1048    wonderfully
95  0.0000           work
96  0.1579          worry
97 -0.1274          worse
                score  frequency  polarity
word
amazing        0.0562          2    0.0056
available     -0.1716          0   -0.0000
awesome        0.0589          1    0.0029
bad           -0.1952          0   -0.0000
best           0.2413          5    0.0603
better        -0.1574          1   -0.0079
bomb           0.0000          1    0.0000
celebrate      0.1124          2    0.0112
classy         0.0000          1    0.0000
clear         -0.0339          0   -0.0000
cold          -0.3143          0   -0.0000
complimentary  0.0039          1    0.0002
consistently  -0.0339          0   -0.0000
cool           0.0000          1    0.0000
criticism      0.0207          1    0.0010
decent         0.3178          2    0.0318
delicious      0.4828          5    0.1207
desirable     -0.2561          0   -0.0000
disappointed   0.0562          1    0.0028
disappointing -0.2804          0   -0.0000
disintegrate   0.0000          1    0.0000
disrespectful -0.1377          0   -0.0000
distraction    0.0000          1    0.0000
downhill      -0.1274          0   -0.0000
enjoyed        0.0207          2    0.0021
enough        -0.0339          0   -0.0000
exaggeration  -0.0339          0   -0.0000
fabulous       0.0000          1    0.0000
fast           0.0039          1    0.0002
favorite       0.0628          2    0.0063
fool           0.0000          1    0.0000
fresh          0.4150          4    0.0830
friendly       0.0000          1    0.0000
fuzzy          0.0000          1    0.0000
gem            0.0589          1    0.0029
good           0.2455          5    0.0614
great          0.2703          6    0.0811
hard           0.0039          1    0.0002
hate           0.0039          1    0.0002
honesty        0.0039          1    0.0002
horrible      -0.2902          0   -0.0000
hot            0.1798          5    0.0450
impressed     -0.3050          0   -0.0000
incredibly     0.1048          1    0.0052
led            0.1048          1    0.0052
lemon          0.0207          1    0.0010
like          -0.0897          3   -0.0135
liked          0.0207          2    0.0021
loud          -0.1525          0   -0.0000
love           0.1472          6    0.0442
luck          -0.2802          0   -0.0000
miserable     -0.0339          0   -0.0000
mistake       -0.0339          0   -0.0000
negative       0.0223          1    0.0011
nice           0.0453          4    0.0091
nicely         0.0039          1    0.0002
oblivious      0.0000          1    0.0000
pains         -0.1274          0   -0.0000
patient        0.1579          1    0.0079
perfect        0.1048          1    0.0052
perfectly     -0.1377          0   -0.0000
popular        0.0000          1    0.0000
positive      -0.0339          0   -0.0000
pretend       -0.2802          0   -0.0000
pretty         0.1618          4    0.0324
pricey         0.0000          1    0.0000
ready          0.1579          1    0.0079
reasonably    -0.0339          0   -0.0000
recommend      0.0562          3    0.0084
recommended    0.1736          1    0.0087
rich           0.0000          1    0.0000
right          0.0000          1    0.0000
rude          -0.1377          0   -0.0000
sad           -0.2561          0   -0.0000
safe           0.0000          1    0.0000
satisfied      0.1048          2    0.0105
skeptical      0.0000          1    0.0000
slow          -0.2804          0   -0.0000
smiling       -0.1377          0   -0.0000
soft           0.0000          1    0.0000
sorry         -0.0339          0   -0.0000
super         -0.0000          2   -0.0000
tender         0.1048          2    0.0105
tired          0.1048          1    0.0052
tremendously  -0.2561          0   -0.0000
trusted        0.1048          1    0.0052
unable        -0.1274          0   -0.0000
unfortunately -0.1514          1   -0.0076
unreal         0.0000          1    0.0000
upscale       -0.2802          0   -0.0000
warm          -0.1318          1   -0.0066
waste         -0.2802          0   -0.0000
weird          0.0039          1    0.0002
well           0.0323          2    0.0032
wonderfully    0.1048          1    0.0052
work           0.0000          1    0.0000
worry          0.1579          1    0.0079
worse         -0.1274          0   -0.0000

/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

               score  frequency  polarity
word
delicious     0.4828          5    0.1207
fresh         0.4150          4    0.0830
hot           0.1798          5    0.0450
celebrate     0.1124          2    0.0112
tender        0.1048          2    0.0105
satisfied     0.1048          2    0.0105
recommended   0.1736          1    0.0087
recommend     0.0562          3    0.0084
patient       0.1579          1    0.0079
worry         0.1579          1    0.0079
incredibly    0.1048          1    0.0052
led           0.1048          1    0.0052
tired         0.1048          1    0.0052
trusted       0.1048          1    0.0052
wonderfully   0.1048          1    0.0052
negative      0.0223          1    0.0011
criticism     0.0207          1    0.0010
lemon         0.0207          1    0.0010
complimentary 0.0039          1    0.0002
nicely        0.0039          1    0.0002

In [36]:
get_top_words(Japanese_polarity_score,'negative',20)

       score  frequency  polarity
word
warm -0.1318          1   -0.0066

In [37]:
Japanese_test_score=test_data(Japanese_test,vectorizer_Jap,svm_Jap)

ramen is good but the takoyaki and curry tonkatsu rice bowls are something else the takoyaki is the best in philly by far  there are generally 3 large chunks of octopus per piece which is the way it is supposed to be but other restraints are too cheap to makegreat place eat there at least once a month
['negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'negative', 'negative', 'positive']
['negative' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'negative' 'positive' 'negative'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'positive' 'negative' 'negative' 'negative' 'positive' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'negative' 'positive'
 'positive' 'negative' 'positive' 'negative' 'negative' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'negative' 'negative' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'negative' 'negative' 'negative' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'negative' 'positive' 'negative' 'positive' 'positive' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive']

In [22]:
print(Japanese_test_score)

0.7111111111111111